
platform :ios, '9.0'
use_frameworks!

target 'HTTPClientDemo' do
  pod 'SwiftyJSON', '~> 3.1.4'
  pod 'Alamofire', '~> 4.4.0'

  target 'HTTPClientDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HTTPClientDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
